name: CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request_target:
    branches: [ "main" ]

jobs:
  basic_ci:
    name: Run Repo CI Tests

    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout Repository âœ…
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }} # The source branch of the pull request
          repository: ${{ github.event.pull_request.head.repo.full_name }} # The repository of the pull request source branch
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0 # Fetch all history for all branches

      - name: ğŸ”¤ Check Spelling ğŸ”¤
        uses: streetsidesoftware/cspell-action@v6
        with:
          treat_flagged_words_as_errors: true
          strict: true
          inline: warning

      - name: Markdown Linting
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: markdownlint.yml
          args: "**/*.md"
  run:
    name: Run Rust CI Tests

    needs: [ basic_ci ]

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        
    steps:
      - name: âœ… Checkout Repository âœ…
        uses: actions/checkout@v4
    
      - name: ğŸ› ï¸ Download Rust Tools ğŸ› ï¸
        uses: ./.github/actions/rust-tool-cache
      
      - name: Add Credentials # Remove once repositories are public
        run: |
          git config --global url."https://${{ secrets.GH_PAT }}@github.com".insteadOf https://github.com
        shell: bash

      - name: Run cargo-fmt
        run: cargo fmt --all --check
        env:
          RUSTC_BOOTSTRAP: 1

      - name: ğŸ§ª Run Tests ğŸ§ª
        run: cargo make coverage

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: target/cobertura.xml
          fail_ci_if_error: false # Expect it to fail while repository is private

      - name: Build std
        run: cargo make build

      - name: Build X64
        run: cargo make -e ARCH=X64 build-arch

      - name: Build AArch64
        run: cargo make -e ARCH=AARCH64 build-arch
